#!/bin/bash

# This is used for docker, to include ros_team_workspace inside docker and auto source it.

# if you did not install ros under /opt/ros/<ros-distro>/ then you have to set the ALTERNATIVE_ROS_<ROS_DISTRO>_LOCATION
# to point to your installation folder e.g. ALTERNATIVE_ROS_ROLLING_LOCATION=/home/user/my_installation_folder/rolling/
# For other ros versions simply add ALTERNATIVE_ROS_<ros-distro>_LOCATION e.g. ALTERNATIVE_ROS_FOXY_LOCATION
ALTERNATIVE_ROS_ROLLING_LOCATION=""

TEAM_LICENSE="Apache License 2.0"

TEAM_REPOSITORY_SERVER="https://github.com"

TEAM_PRIVATE_CONFIG_PATH=""

# ros_team_workspace is always at same location inside docker.
source /opt/RosTeamWS/ros_ws_ROS_DUMMY_VERSION/src/ros_team_workspace/setup.bash

# User specific setup / variables

#export CYCLONEDDS_URI='<CycloneDDS><Domain><General><NetworkInterfaceAddress>ADD_HERE_INTERFACE_NAME</NetworkInterfaceAddress></General></Domain></CycloneDDS>'

export ROS_DOMAIN_ID=42  # Set your Domain ID if you are in a network with multiple computers

# Logging setup
# export RCUTILS_LOGGING_CONFIG_FILE="/home/deniss/workspace/ros2_logging_config"
#export RCUTILS_CONSOLE_OUTPUT_FORMAT="[{severity} {time}] [{name}]: {message} ({function_name}() at {file_name}:{line_number})"  # Custom logging format
export RCUTILS_COLORIZED_OUTPUT=1
#export RCUTILS_LOGGING_USE_STDOUT=1  # force all logging output to stdout

# WORKSPACES
