name: $Ros_distro$ Source Build
on:
  push:
    branches:
      - $branch$
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 3 * * *'

jobs:
  source:
    uses: ./.github/workflows/reusable-ros-tooling-source-build.yml
    with:
      ros_distro: $ROS_DISTRO$
      ref: $branch$
