name: Build
on:
  pull_request:
  push:
    branches:
      - $ROS_DISTRO$
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '28 6 * * *'

jobs:
  binary:
    name: binary build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: $ROS_DISTRO$, ROS_REPO: main}
          - {ROS_DISTRO: $ROS_DISTRO$, ROS_REPO: testing}
    env:
      UPSTREAM_WORKSPACE: Universal_Robots_ROS2_Driver.repos
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
