name: Build
on:
  pull_request:
  push:
    branches:
      - $ROS_DISTRO$
  #schedule:
    ## Run every morning to detect flakiness and broken dependencies
    #- cron: '28 6 * * *'

jobs:
  ci_binary:
    name: $ROS_DISTRO$ binary job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: $ROS_DISTRO$, ROS_REPO: main}
          - {ROS_DISTRO: $ROS_DISTRO$, ROS_REPO: testing}
    env:
      UPSTREAM_WORKSPACE: $NAME$.ci.repos
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}

## CI build from source is commented out by default to save time on runner
  #ci_source:
    #name: $ROS_DISTRO$ source job
    #runs-on: ubuntu-20.04
    #strategy:
      #fail-fast: false
    #steps:
      #- uses: ros-tooling/setup-ros@0.0.26
        #with:
          #required-ros-distributions: $ROS_DISTRO$
      #- uses: ros-tooling/action-ros-ci@0.1.0
        #with:
          #target-ros2-distro: $ROS_DISTRO$
          ## build all packages listed in the meta package
          #package-name:
            #$NAME$
          #vcs-repo-file-url: |
            #https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/$NAME$.repos
          #colcon-mixin-name: coverage-gcc
          #colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
      #- uses: codecov/codecov-action@v1.0.14
        #with:
          #file: ros_ws/lcov/total_coverage.info
          #flags: unittests
          #name: codecov-umbrella
      #- uses: actions/upload-artifact@v1
        #with:
          #name: colcon-logs-${{ matrix.os }}
          #path: ros_ws/log
