name: $Ros_distro$ RHEL Binary Build
on:
  pull_request:
    branches:
      - $branch$
  push:
    branches:
      - $branch$
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 1 * * *'


jobs:
  $ROS_DISTRO$_rhel_binary:
    name: $Ros_distro$ RHEL binary build
    runs-on: ubuntu-latest
    env:
      ROS_DISTRO: $ROS_DISTRO$
    container: jaronl/ros:$ROS_DISTRO$-alma
    steps:
      - uses: actions/checkout@v2
        with:
          path: src/$NAME$
      - run: |
          rosdep update
          rosdep install -iy --from-path src/$NAME$
          source /opt/ros/${{ env.ROS_DISTRO }}/setup.bash
          colcon build
          colcon test
