name: Build and deploy pages

on:
  push:
    branches:
      - master
      - foxy
  

  deploy-multiversion:
    name: Deploy Multiversion
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        cache: 'pip'
    - name: Install Python dependencies
      run: |
        cd docs/
        python -m pip install --upgrade pip
        pip install --upgrade --requirement requirements.txt
    - name: Build multiversion with API
      run: |
        cd docs/
        make multiversion
    - name: Deploy Pages
      if: ${{ success() }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html