/**:
  ros__parameters:
    # from launch file
    capabilities: move_group/MoveGroupExecuteTrajectoryAction
    publish_planning_scene: True
    publish_geometry_updates: True
    publish_state_updates: True
    publish_transforms_updates: True

    # kinematics
    robot_description_kinematics:
      myrobot_manipulator:
        kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        kinematics_solver_search_resolution: 0.005
        kinematics_solver_timeout: 0.005
        kinematics_solver_attempts: 3

    # joint limits
    robot_description_planning:
      default_velocity_scaling_factor: 0.1
      default_acceleration_scaling_factor: 0.1

      # Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
      # Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
      joint_limits:
        joint1:
          has_velocity_limits: true
          max_velocity: 1.7453292519943295
          has_acceleration_limits: true
          max_acceleration: 5.0
        joint2:
          has_velocity_limits: true
          max_velocity: 1.5707963267948966
          has_acceleration_limits: true
          max_acceleration: 5.0
        joint3:
          has_velocity_limits: true
          max_velocity: 1.5707963267948966
          has_acceleration_limits: true
          max_acceleration: 5.0
        joint4:
          has_velocity_limits: true
          max_velocity: 2.9670597283903604
          has_acceleration_limits: true
          max_acceleration: 5.0
        joint5:
          has_velocity_limits: true
          max_velocity: 2.0943951023931953
          has_acceleration_limits: true
          max_acceleration: 5.0
        joint6:
          has_velocity_limits: true
          max_velocity: 3.3161255787892263
          has_acceleration_limits: true
          max_acceleration: 5.0

    # Moveit Controllers
    moveit_manage_controllers: false
    trajectory_execution:
      allowed_execution_duration_scaling: 1.2
      allowed_goal_duration_margin: 0.5
      allowed_start_tolerance: 0.01

    moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
    moveit_simple_controller_manager:
      controller_names:
        - joint_trajectory_controller

      joint_trajectory_controller:
        type: FollowJointTrajectory
        action_ns: follow_joint_trajectory
        default: true
        joints:
          - joint1
          - joint2
          - joint3
          - joint4
          - joint5
          - joint6

    # OMPL planning
    move_group:
      planning_plugins: 
        - ompl_interface/OMPLPlanner
      request_adapters:
        - default_planning_request_adapters/ResolveConstraintFrames
        - default_planning_request_adapters/ValidateWorkspaceBounds
        - default_planning_request_adapters/CheckStartStateBounds
        - default_planning_request_adapters/CheckStartStateCollision
      response_adapters:
        - default_planning_response_adapters/AddTimeOptimalParameterization
        - default_planning_response_adapters/ValidateSolution
        - default_planning_response_adapters/DisplayMotionPath
      myrobot_manipulator:
        planner_configs:
          SBLkConfigDefault:
            type: geometric::SBL
            range: 0.0  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
          ESTkConfigDefault:
            type: geometric::EST
            range: 0.0  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0 setup()
            goal_bias: 0.05  # When close to goal select goal, with this probability. default: 0.05
          LBKPIECEkConfigDefault:
            type: geometric::LBKPIECE
            range: 0.0  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
            border_fraction: 0.9  # Fraction of time focused on boarder default: 0.9
            min_valid_path_fraction: 0.5  # Accept partially valid moves above fraction. default: 0.5
          BKPIECEkConfigDefault:
            type: geometric::BKPIECE
            range: 0.0  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
            border_fraction: 0.9  # Fraction of time focused on boarder default: 0.9
            failed_expansion_score_factor: 0.5  # When extending motion fails, scale score by factor. default: 0.5
            min_valid_path_fraction: 0.5  # Accept partially valid moves above fraction. default: 0.5
          KPIECEkConfigDefault:
            type: geometric::KPIECE
            range: 0.0  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
            goal_bias: 0.05  # When close to goal select goal, with this probability. default: 0.05
            border_fraction: 0.9  # Fraction of time focused on boarder default: 0.9 (0.0,1.]
            failed_expansion_score_factor: 0.5  # When extending motion fails, scale score by factor. default: 0.5
            min_valid_path_fraction: 0.5  # Accept partially valid moves above fraction. default: 0.5
          RRTkConfigDefault:
            type: geometric::RRT
            range: 0.0  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
            goal_bias: 0.05  # When close to goal select goal, with this probability? default: 0.05
          RRTConnectkConfigDefault:
            type: geometric::RRTConnect
            range: 0.0  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
          RRTstarkConfigDefault:
            type: geometric::RRTstar
            range: 0.0  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
            goal_bias: 0.05  # When close to goal select goal, with this probability? default: 0.05
            delay_collision_checking: 1  # Stop collision checking as soon as C-free parent found. default 1
          TRRTkConfigDefault:
            type: geometric::TRRT
            range: 0.0  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
            goal_bias: 0.05  # When close to goal select goal, with this probability? default: 0.05
            max_states_failed: 10  # when to start increasing temp. default: 10
            temp_change_factor: 2.0  # how much to increase or decrease temp. default: 2.0
            min_temperature: 10e-10  # lower limit of temp change. default: 10e-10
            init_temperature: 10e-6  # initial temperature. default: 10e-6
            frountier_threshold: 0.0  # dist new state to nearest neighbor to disqualify as frontier. default: 0.0 set in setup()
            frountierNodeRatio: 0.1  # 1/10, or 1 nonfrontier for every 10 frontier. default: 0.1
            k_constant: 0.0  # value used to normalize expression. default: 0.0 set in setup()
          PRMkConfigDefault:
            type: geometric::PRM
            max_nearest_neighbors: 10  # use k nearest neighbors. default: 10
          PRMstarkConfigDefault:
            type: geometric::PRMstar
        ##Note: commenting the following line lets moveit chose RRTConnect as default planner rather than LBKPIECE
        #projection_evaluator: joints(shoulder_pan_joint,shoulder_lift_joint)
        longest_valid_segment_fraction: 0.01