# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint1:
    has_velocity_limits: true
    max_velocity: 1.7453292519943295
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint2:
    has_velocity_limits: true
    max_velocity: 1.5707963267948966
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint3:
    has_velocity_limits: true
    max_velocity: 1.5707963267948966
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint4:
    has_velocity_limits: true
    max_velocity: 2.9670597283903604
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint5:
    has_velocity_limits: true
    max_velocity: 2.0943951023931953
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint6:
    has_velocity_limits: true
    max_velocity: 3.3161255787892263
    has_acceleration_limits: true
    max_acceleration: 5.0