# Copyright (c) 2024, Stogl Robotics Consulting UG (haftungsbeschränkt)
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# Source of this file are templates in https://github.com/StoglRobotics/ros_team_workspace repository.

/**:
  ros__parameters:
#-------- Moveit controllers
    moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
    moveit_simple_controller_manager:
      controller_names:
        - joint_trajectory_controller       # add or remove controllers as necessary

      joint_trajectory_controller:
        type: FollowJointTrajectory
        action_ns: follow_joint_trajectory
        default: true
        joints:
          - joint1
          - joint2
          - joint3
          - joint4
          - joint5
          - joint6

#-------- kinematics
    robot_description_kinematics:
      $ROBOT_NAME$_manipulator:
        kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        kinematics_solver_search_resolution: 0.005
        kinematics_solver_timeout: 0.005
        kinematics_solver_attempts: 3

#-------- joint limits
    robot_description_planning:
      default_velocity_scaling_factor: 0.1
      default_acceleration_scaling_factor: 0.1
      # Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
      # Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
      joint_limits:
        joint1:
          has_velocity_limits: true
          max_velocity: 1.7453292519943295
          has_acceleration_limits: true
          max_acceleration: 5.0
        joint2:
          has_velocity_limits: true
          max_velocity: 1.5707963267948966
          has_acceleration_limits: true
          max_acceleration: 5.0
        joint3:
          has_velocity_limits: true
          max_velocity: 1.5707963267948966
          has_acceleration_limits: true
          max_acceleration: 5.0
        joint4:
          has_velocity_limits: true
          max_velocity: 2.9670597283903604
          has_acceleration_limits: true
          max_acceleration: 5.0
        joint5:
          has_velocity_limits: true
          max_velocity: 2.0943951023931953
          has_acceleration_limits: true
          max_acceleration: 5.0
        joint6:
          has_velocity_limits: true
          max_velocity: 3.3161255787892263
          has_acceleration_limits: true
          max_acceleration: 5.0
    
#-------- other
    moveit_manage_controllers: false
    trajectory_execution:
      allowed_execution_duration_scaling: 1.2
      allowed_goal_duration_margin: 0.5
      allowed_start_tolerance: 0.01
    capabilities: move_group/MoveGroupExecuteTrajectoryAction
    publish_planning_scene: True
    publish_geometry_updates: True
    publish_state_updates: True
    publish_transforms_updates: True

    