# This is a format job. Pre-commit has a first-party GitHub action, so we use
# that: https://github.com/pre-commit/action

name: Format and Lint
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - update_ci

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@master
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        cache: 'pip'
    - name: Install clang-format-10
      run: sudo apt-get install clang-format-10
    - uses: pre-commit/action@v2.0.0
