name: Lint
on:
  workflow_dispatch:
  pull_request:

jobs:
  ament_lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linter: [cppcheck, cpplint, lint_cmake]
        arguments: [""]
        include:
          - linter: copyright
            arguments: "--exclude CONTRIBUTING.md conf.py test_robot_description.launch.py view_robot.launch.py dummy_controller.cpp dummy_controller.hpp test_dummy_controller.cpp test_dummy_controller.hpp test_load_dummy_controller.cpp robot_hardware_interface.cpp robot_hardware_interface.hpp test_robot_hardware_interface.cpp visibility_control.h robot_ros2_control.launch.py test_forward_position_controller.launch.py test_joint_trajectory_controller.launch.py"
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@master
    - uses: ros-tooling/action-ros-lint@master
      with:
        distribution: galactic
        linter: ${{ matrix.linter }}
        arguments: ${{ matrix.arguments }}
        package-name:
          ros_team_workspace
