name: Lint
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - update_ci

jobs:
  ament_lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linter: [copyright, cppcheck, copyright, lint_cmake]
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@master
    - uses: ros-tooling/action-ros-lint@master
      with:
        distribution: rolling
        linter: ${{ matrix.linter }}
        package-name:
          ros_team_workspace
