name: Lint
on:
  workflow_dispatch:
  pull_request:

jobs:
  ament_lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    env:
      AMENT_CPPCHECK_ALLOW_SLOW_VERSIONS: True
    strategy:
      fail-fast: false
      matrix:
        linter: [cppcheck, cpplint, lint_cmake]
        arguments: [""]
        include:
          - linter: copyright
            arguments: "--exclude docs/conf.py"
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@master
    - uses: ros-tooling/action-ros-lint@master
      with:
        distribution: rolling
        linter: ${{ matrix.linter }}
        arguments: ${{ matrix.arguments }}
        # package-name:
          # ros_team_workspace
