name: Lint
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - update_ci

jobs:
  ament_lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-ros-galactic-ros-base-latest
      options: -u root
    strategy:
      fail-fast: false
      matrix:
        linter: [cppcheck, cpplint, lint_cmake]
        arguments: [""]
        include:
          - linter: copyright
            arguments: "--exclude=templates/"
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@master
    - uses: ros-tooling/action-ros-lint@master
      with:
        distribution: rolling
        linter: ${{ matrix.linter }}
        arguments: ${{ matrix.arguments }}
        package-name:
          ros_team_workspace
