name: Check Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - foxy

jobs:
  build-multiversion:
    name: Deploy Multiversion
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        cache: 'pip'
    - name: Install Python dependencies
      run: |
        cd docs/
        python -m pip install --upgrade pip
        pip install --upgrade --requirement requirements.txt
    - name: Build multiversion
      run: |
        cd docs/
        make multiversion
    - name: Check HTML
        uses: chabad360/htmlproofer@master
        with:
          directory: "./docs/_build/html/"
